---
# Configuration for https://pre-commit.com
#
# Add custom Zeropoint pre-comit hooks in the https://bitbucket.org/zpt/pre-commit-hooks
#

default_language_version:
  python: python3

repos:
  # - repo: git@bitbucket.org:zpt/pre-commit-hooks
  #   rev: master
  #   hooks:
  #     - id: jenkinsfile-lint

  - repo: local
    hooks:
      - id: unit-test
        name: Python Doc Tests
        language: system
        types: [python]
        files: semver/*
        pass_filenames: false
        entry: "python3 semver/conanfile.py"

  - repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
      - id: black
        name: Format Python code using black

  - repo: https://github.com/codespell-project/codespell
    rev: v2.0.0
    hooks:
      - id: codespell
        args:
          - -r "[a-zA-Z0-9\-'’\`]+"

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-added-large-files
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
      - id: detect-private-key
      - id: trailing-whitespace

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.0.0
    hooks:
      - id: forbid-binary

